name: token scope

on:
  issues:
   
jobs:
  token_scope:
    name: check token scopes
    runs-on: ubuntu-latest
    steps:
      - name: check token scope
        run: |
          curl https://api.github.com/user/blocks \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' 
          curl https://api.github.com/user/emails \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' 
          curl https://api.github.com/user/gpg_keys  \
           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
           --header 'content-type: application/json'  
          curl https://api.github.com/user/keys  \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' 
          curl https://api.github.com/repos/wewe679/test1/pages
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' 
