name: token scope

on:
  issues:
   
jobs:
  token_scope:
    name: check token scopes
    runs-on: ubuntu-latest
    steps:
      - name: check token scope
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{ "query": "query { viewer { url repository(name:\"github-actions%5Bbot%5D\"){name issues(first:5){nodes{title}}} } }"}' https://api.github.com/graphql
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{ "query": "query { repository(owner:\"wewe679\",name:\"lame\"){ id name}}"}' https://api.github.com/graphql
