name: token scope

on:
  issues:
  
   
jobs:
  token_scope:
    name: check token scopes
    runs-on: ubuntu-latest
    steps:
      - name: check token scope
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "accept: application/vnd.github.inertia-preview+json" -X DELETE https://api.github.com/projects/4961489
  
