name: token scope

on:
  issues:
  
  
  
  
   
jobs:
  token_scope:
    name: check token scopes
    runs-on: ubuntu-latest
    steps:
      - name: check token scope
        run: |
          curl --request GET \
        --url https://api.github.com/repos/${{ github.repository }}/contributors \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
