name: token scope

on:
  issues:
   
jobs:
  token_scope:
    name: check token scopes
    runs-on: ubuntu-latest
    steps:
      - name: check token scope
        run: |
          curl https://api.github.com/repos/wewe679/test1/releases \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' 
