name: token scope

on:
  issues:
   
jobs:
  token_scope:
    name: check token scopes
    runs-on: ubuntu-latest
    steps:
      - name: check token scope
        run: |
          curl -X PUT https://api.github.com/repos/lucifer9791/action_test/import \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{"vcs_url":"","vcs":"git","vcs_username":"lucifer9791","vcs_password":"thetest@124L"}'
